version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_3ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_3ban_static:/data/static/
      - gis_3ban_media:/data/media/

  django:
    image: gis_3ban_django:3
    networks:
      - gis_3ban_network
    volumes:
      - gis_3ban_static:/home/gis_3ban_1/staticfiles/
      - gis_3ban_media:/home/gis_3ban_1/media/

networks:
  gis_3ban_network:

volumes:
  gis_3ban_static:
  gis_3ban_media:
